version: '3.0'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1G -Xmx1G
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=BKz2Xbh1_k4oUalN4V96
    privileged: true
    deploy:
      resources:
        limits:
          memory: 1G
  kibana:
    image: kibana:8.8.2
    ports:
      - "5601:5601"
    environment:
      - CONTAINER_TIMEZONE=Asia/Shanghai
    privileged: true
  logstash:
    image: logstash:8.8.2
    ports:
      - "5044:5044"
      - "514:514"
    volumes:
#      - "./logstash/config:/usr/share/logstash/config"
      - "./logstash/pipeline:/usr/share/logstash/pipeline"
    environment:
      - CONTAINER_TIMEZONE=Asia/Shanghai
    privileged: true